CREATE TABLE T_USER (
 id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 email VARCHAR(320) NOT NULL,
 mobile_phone VARCHAR(11) NOT NULL,
 password CHAR(64),
 fullname VARCHAR(20) NOT NULL,
 sex CHAR(1) NOT NULL,
 disabled TINYINT DEFAULT 0 NOT NULL,
 create_time TIMESTAMP NOT NULL
);


